server:
  port: 10103
logging:
  level:
    com.hellozjf.test.springboot: debug
file:
  writeToFile: false
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://aliyun.hellozjf.com:3306/springboot?characterEncoding=utf-8&useSSL=false&autoReconnect=true
    username: root
    password: Zjf@1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
